default:
    just --list

@migrations +args="":
    mv ../petring.db .
    cargo run --release -- {{ args }}
    mv petring.db ../

@prepare-bin:
    cargo chef --prepare --recipe-path recipe.json

@cook-bin:
    cargo chef cook --release --recipe-path recipe.json
