# You will need a .env for this docker-compose file

services:
  petring:
    container_name: petring
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}

    ports:
      - 8080:8080

    # networks: # For use with traefik
    #   - proxy

    volumes:
      - ./petring.db:/app/petring.db
      - ./petring.toml:/app/petring.toml
      - ./frontend/:/app/frontend/
# networks: # For use with traefik
#   proxy:
#     name: "proxy"
#     external: true
