# NOTE: You only need this file if you're using traefik

# services:
#   petring-web:
#     labels:
#       traefik.enable: true # Enable traefik
#       traefik.docker.network: proxy # Needs to match the network name in docker-compose.yml
#
#       traefik.http.routers.petring-web.rule: Host(``) # Set hostname for webserver here
#       traefik.http.routers.petring-web.tls: true # We recommend using traefik's builtin support for acme cert resolvers.
#       traefik.http.routers.petring-web.tls.certresolver: letsencrypt # Initialize a certresolver for this to work (I recommend letsencrypt)
#       traefik.http.services.petring-web.loadbalancer.server.port: 8080 # You can only chang this after modifying petring-web.toml
#
#   petring-api:
#     labels:
#       traefik.enable: true # Enable traefik
#       traefik.docker.network: proxy # Needs to match the network name in docker-compose.yml
#
#       traefik.http.routers.petring-api.rule: Host(``) # Set hostname for api here
#       traefik.http.routers.petring-api.tls: true # We recommend using traefik's builtin support for acme cert resolvers.
#       traefik.http.routers.petring-api.tls.certresolver: letsencrypt # Initialize a certresolver for this to work (I recommend letsencrypt)
#      traefik.http.services.petring-api.loadbalancer.server.port: 8081 # You can only change this after modifying petring-api.toml
