# You will need a .env for this docker-compose file

# Deployment :
# uncomment the entire watchtower section
# uncomment traefik if needed

services:
  petring-web:
    container_name: petring-web
    build: ./web # <- Comment this out and uncomment the thing below if you're not cloning the repo
    # image: ghcr.io/h4rldev/petring-web:latest
    labels:
      com.centurylinklabs.watchtower.scope: petring-web

    ports:
      - 8080:8080

    volumes:
      - ./petring-web.toml:/app/petring-web.toml
      - ./frontend/:/app/frontend/

  petring-api:
    container_name: petring-api
    build: ./api # <- Comment this out and uncomment the thing below if you're not cloning the repo
    # image: ghcr.io/h4rldev/petring-api:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}
    labels:
      com.centurylinklabs.watchtower.scope: petring-api

    ports:
      - 8081:8081

    volumes:
      - ./petring-api.toml:/app/petring-api.toml
      - ./petring.db:/app/petring.db

  #   watchtower: # For auto-updates
  #     image: containrrr/watchtower
  #     container_name: watchtower_petring
  #     volumes:
  #       - "/var/run/docker.sock:/var/run/docker.sock"
  #     command: --interval 30 --scope petring-web --scope petring-api
  #     labels:
  #       com.centurylinklabs.watchtower.scope: petring-web
  #       com.centurylinklabs.watchtower.scope: petring-api
