[site]
root = "static"
error = "static/404.html"

[tls]
cert = ".certs/cert1.pem"
key = ".certs/privkey1.pem"
enable = true

[network]
# When tls is off, the http port will be the port
# When tls is on, the https port will be the port
ip = "0.0.0.0"
port = 8080

[logging]
level = "INFO"
